### PR TITLE
Support boolean "additionalProperties"

### PR DESCRIPTION
**Pull request by saroad2**
When defining an object in json schema one can add the "additionalProperties" field which direct how to handle additional keys given in the raw data, as described [here](https://json-schema.org/understanding-json-schema/reference/object.html#properties). If it's set to "false", we should raise an error when additional keys are presented.
Implemented this use-case.

**Pay attention**: one can also set  "additionalProperties" to be a *definition* of the allowed additional properties. This is a little bit more complex, so I'll try to implement it in a future PR.

### CODE REVIEW

**Comment by SF-Zhou** [comment]
JSON schema contains various rules, such as type checking, min/max value checking. I find that it's complex to validate these rules in this tiny tool. So I prefer to use `jsonschema` and `json-schema-to-class` together, like `https://github.com/FebruaryBreeze/torch-basic-models/blob/master/torch_basic_models/resnet.py#L93`, and use the former to validate schema.

**Comment by saroad2** [comment]
I understand.

So, maybe the right thing to do is to add a `--validate` flag to *json-schema-to-class* that adds a validation using the *jsonschema* module of the input. In that way the users won't need to write additional code in order to ad valdiations.

What do you think?

**Comment by SF-Zhou** [comment]
> I understand.
> 
> So, maybe the right thing to do is to add a `--validate` flag to _json-schema-to-class_ that adds input validation using the _jsonschema_ module. In that way, the users won't need to write additional code in order to add validations.
> 
> What do you think?

OK. In this way the content of schema file need to be stored in the generated files and *jsonschema* is required.

**Comment by saroad2** [comment]
Yes.

Do you think it's a good idea?
If you do, I'll make the PR

**Comment by SF-Zhou** [comment]
> Yes.
> 
> Do you think it's a good idea?
> If you do, I'll make the PR

I think it's fine. It may be assumed that users who use `--validate` flag accept such a situation.

**Comment by saroad2** [comment]
Opened new PR and closing this one

**Pull request closed without merging**
